#18 c'est la version, et alpine c'est le linux léger. En gros c'est qu'est ce que je dois lancer
FROM node:18-alpine 
# c'est comme un mkdir 
WORKDIR /app
COPY package*.json
RUN npm install --production --no-audit --no-fund
#Créer un user dédier
ARG UID=1
HEALTHCHECK --interval=30s --timeout=3s --retries=3 
COPY . .
EXPOSE 5000
ENV PORT=5000
CMD ["node", "server.js"]
